version: "3.7"
volumes:
  pgsql-data:
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgsql-data
        target: /var/lib/postgresql/data
